// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "runtimeDescriptor": string;
      "configPath": string;
      "tier": string;
      "ocrMode": string;
      "imageAnalysis": boolean;
      "pageRange": string;
    };
  }
}
