import { createHash } from "node:crypto";
import console from "node:console";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { basename, dirname, resolve } from "node:path";
import process from "node:process";
import { fileURLToPath, URL } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const output = resolve(
  process.argv[2] ?? resolve(root, ".scaffold/build/install-runtime.py"),
);
const sha256 = (bytes) => createHash("sha256").update(bytes).digest("hex");
const manifestText = await readFile(
  resolve(root, "runtime/release.json"),
  "utf8",
);
const manifest = JSON.parse(manifestText);
const pkg = JSON.parse(await readFile(resolve(root, "package.json"), "utf8"));
if (
  manifest.plugin.id !== pkg.config.addonID ||
  manifest.plugin.version !== pkg.version
) {
  throw new Error("Release manifest plugin identity differs from package.json");
}
const locks = {};
for (const [name, profile] of Object.entries(manifest.profiles)) {
  const bytes = await readFile(resolve(root, "runtime", profile.lock));
  if (sha256(bytes) !== profile.sha256) {
    throw new Error(`Release lock checksum mismatch: ${name}`);
  }
  locks[name] = bytes.toString("utf8");
}
let source = await readFile(
  resolve(root, "scripts/install_runtime.py"),
  "utf8",
);
for (const [declaration, value] of [
  ["EMBEDDED_MANIFEST: str | None", manifestText],
  ["EMBEDDED_LOCKS: dict[str, str] | None", locks],
]) {
  const marker = `${declaration} = None`;
  if (source.split(marker).length !== 2) {
    throw new Error(`Expected one installer declaration: ${declaration}`);
  }
  source = source.replace(
    marker,
    () => `${declaration} = ${JSON.stringify(value)}`,
  );
}
source = `# Generated by scripts/build_runtime_installer.mjs; edit the source files.\n${source}`;
await mkdir(dirname(output), { recursive: true });
await writeFile(output, source);
await writeFile(`${output}.sha256`, `${sha256(source)}  ${basename(output)}\n`);
console.log(output);
